name: Cypress CI Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@elistone'
      - run: npm install
      - run: npm run test:cypress
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets.READ_PACKAGES_PAT}}
